# Generated by Django 5.2 on 2025-04-21 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(default='No description', max_length=255)),
                ('pp', models.ImageField(blank=True, default='cover2.jpg', null=True, upload_to='Profile_picture')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('access_token', models.CharField(blank=True, max_length=265)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('connections', models.ManyToManyField(blank=True, related_name='connections', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
