# Generated by Django 5.2 on 2025-04-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pp',
            field=models.ImageField(blank=True, default='cover2.jpeg', null=True, upload_to='Profile_picture'),
        ),
    ]
